#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const OUT_PATH = path.join(ROOT, 'js', 'config.local.js');

const RECOGNIZED_KEYS = [
  'GTM_CONTAINER_ID',
  'FB_PIXEL_ID',
  'KLAVIYO_PUBLIC_KEY',
  'KLAVIYO_LIST_ID',
  'REDIRECT_URL',
  'TOTAL_STEPS',
];

const NUMERIC_KEYS = new Set(['TOTAL_STEPS']);

function parseEnv(source) {
  const out = {};
  source.split('\n').forEach((raw) => {
    const line = raw.trim();
    if (!line || line.startsWith('#')) return;
    const eq = line.indexOf('=');
    if (eq === -1) return;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  });
  return out;
}

if (!fs.existsSync(ENV_PATH)) {
  console.error(
    '[build-config] .env not found. Copy .env.example to .env and fill in your values.',
  );
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(ENV_PATH, 'utf8'));

const overrides = {};
RECOGNIZED_KEYS.forEach((key) => {
  const raw = env[key];
  if (raw === undefined || raw === '') return;
  overrides[key] = NUMERIC_KEYS.has(key) ? Number(raw) : raw;
});

const body =
  '// Generated by scripts/build-config.js from .env — do not edit by hand.\n' +
  `Object.assign(window.CONFIG, ${JSON.stringify(overrides, null, 2)});\n`;

fs.writeFileSync(OUT_PATH, body);
console.log(
  `[build-config] wrote ${Object.keys(overrides).length} keys to ${path.relative(ROOT, OUT_PATH)}`,
);
